### ISSUE TITLE
Remove isSupportRtl in AndroidManifest.xml

### ISSUE THREAD

**Issue by abangfadli** [kayvannj/PermissionUtil#11]
It will merge the AndroidManifest.xml with the one in my project and thus making my project has support for rtl. Not everyone want to support rtl and I haven't figured out a way to exclude AndroidManifest.xml without having to clone the project yet.

Do you need that particular tags for the library to function?

**Comment by kayvannj** [comment]
I'll remove all the unnecessary tags in manifest with https://github.com/kayvannj/PermissionUtil/issues/10 and it will solve your problem. But in the mean time you can use `tools:replace="attr, ..."` in your application tag to address this issue. refer to [this](https://developer.android.com/studio/build/manifest-merge.html) page for more info on that.
