### ISSUE TITLE
Support for permission-group 

### ISSUE THREAD

**Issue by mlostekk** [kayvannj/PermissionUtil#5]
Hello,

first of all great tool. But do you plan support for the manifest tag "permission-group"?

**Comment by kayvannj** [comment]
Hey, Sorry for late response,
I implemented the library based on this documentation http://developer.android.com/training/permissions/requesting.html and as you can find at http://developer.android.com/guide/topics/security/permissions.html#normal-dangerous you only need to ask for one permission in each group. There is no support for permission groups at the moment (and I don't see the need for one).
